-- Generated from template

require('util')
require('physics')
require('particleunit')
require('reflex')

--[[if ReflexGameMode == nil then
    print ( '[REFLEX] creating reflex game mode' )
	  ReflexGameMode = class({})
end]]

function Precache( context )
	--[[
		Precache things we know we'll use.  Possible file types include (but not limited to):
			PrecacheResource( "model", "*.vmdl", context )
			PrecacheResource( "soundfile", "*.vsndevts", context )
			PrecacheResource( "particle", "*.vpcf", context )
			PrecacheResource( "particle_folder", "particles/folder", context )
	]]
		--PrecacheUnitByNameSync('npc_dota_danger_indicator', context)
		--[[PrecacheUnitByNameSync('npc_dota_hero_ancient_apparition', context)
		PrecacheUnitByNameSync('npc_dota_hero_antimage', context)
		PrecacheUnitByNameSync('npc_dota_hero_axe', context)
		PrecacheUnitByNameSync('npc_dota_hero_bane', context)
		PrecacheUnitByNameSync('npc_dota_hero_beastmaster', context)
		PrecacheUnitByNameSync('npc_dota_hero_bloodseeker', context)
		PrecacheUnitByNameSync('npc_dota_hero_chen', context)
		PrecacheUnitByNameSync('npc_dota_hero_crystal_maiden', context)
		PrecacheUnitByNameSync('npc_dota_hero_dark_seer', context)
		PrecacheUnitByNameSync('npc_dota_hero_dazzle', context)
		PrecacheUnitByNameSync('npc_dota_hero_magnataur', context)

		PrecacheResource("particle_folder", "particles/units/heroes/hero_antimage", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_bloodseeker", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_crystalmaiden", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_drow", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_mirana", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_morphling", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_puck", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_pudge", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_vengeful", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_zuus", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_lina", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_enigma", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_sniper", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_queenofpain", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_venomancer", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_faceless_void", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_skeletonking", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_death_prophet", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_rattletrap", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_life_stealer", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_dark_seer", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_omniknight", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_batrider", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_ancient_apparition", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_gyrocopter", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_alchemist", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_invoker", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_obsidian_destroyer", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_meepo", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_disruptor", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_siren", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_keeper_of_the_light", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_wisp", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_magnataur", context)
		--PrecacheResource("particle", "particles/units/heroes/hero_magnataur/magnataur_shockwave.vpcf", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_skywrath_mage", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_abaddon", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_ember_spirit", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_earth_spirit", context)
		PrecacheResource("particle_folder", "particles/units/heroes/hero_windrunner", context)
		PrecacheResource("particle_folder", "particles/frostivus_herofx", context)
		PrecacheResource("particle_folder", "particles/frostivus_gameplay", context)
		PrecacheResource("particle_folder", "particles/test_particle", context)
		--PrecacheResource("particle_folder", "particles/reflex_puck", context)
		--PrecacheResource("particle_folder", "particles/nian_gameplay", context)
		PrecacheResource("particle_folder", "particles/generic_aoe_shockwave_1/generic_aoe_shockwave_1", context)
		PrecacheResource("particle_folder", "particles/generic_gameplay", context)
		PrecacheResource("particle_folder", "particles/econ/generic/generic_timer", context)
		--PrecacheResource("particle_folder", "particles/reflex_ember", context)
		--PrecacheResource("particle_folder", "particles/reflex_particles", context)
		PrecacheResource("particle_folder", "particles/items_fx", context)
		PrecacheResource("particle_folder", "particles/items2_fx", context)
		--PrecacheResource("particle_folder", "particles/econ/generic", context)
		PrecacheResource("particle_folder", "particles/newplayer_fx", context)

		PrecacheModel("models/heroes/rattletrap/rattletrap_cog.vmdl", context)
		PrecacheModel("models/heroes/nightstalker/nightstalker.vmdl", context)
		PrecacheModel("models/heroes/lycan/lycan_wolf.vmdl", context)
		PrecacheModel("models/development/invisiblebox.vmdl", context)
		PrecacheModel("models/heroes/pudge/weapon.vmdl", context)

		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_antimage.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_puck.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_vengefulspirit.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_queenofpain.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_skeletonking.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_rattletrap.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_life_stealer.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_dark_seer.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_batrider.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ancient_apparition.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_alchemist.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_lycan.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_meepo.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_disruptor.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_naga_siren.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_keeper_of_the_light.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_magnataur.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts", context)
		PrecacheResource("soundfile", "soundevents/game_sounds_custom.vsndevts", context)]]
end

-- Create the game mode when we activate
function Activate()
	GameRules.AddonTemplate = ReflexGameMode()
	GameRules.AddonTemplate:InitGameMode()
end